version: '3'

networks:
    backend:


services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: rcf-php
        ports:
            - 8000:80
        volumes:
            - ./src:/var/www/html
        networks:
            - backend
    mysql:
        image: mysql
        container_name: rfc-mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laracast
            MYSQL_USER: mohammad
            MYSQL_PASSWORD: secret
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - backend
    phpmyadmin:
        image: phpmyadmin
        container_name: rfc-phpmyadmin
        ports:
            - 800:80
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
        networks:
            - backend
    nginx:
        image: nginx:stable-alpine
        container_name: rfc-nginx
        ports:
            - 80:80
        volumes:
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - mysql
            - php
        networks:
            - backend
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        depends_on:
            - mysql
        entrypoint: ['php','/var/www/html/artisan']
        networks:
            - backend
    composer:
        image: composer:2.4.4
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - backend
